
struct Sq is
    l : i32 := 0;
end

func add(n1 : i32, n2 : i32) -> i32 is
    n1 := 20;
    n3 := 20;
    var n1 : i32 := 20;
    return x + y;
end

func main is
    var y : i32 := x;
    var x : i32 := 10;
    var x : i32 := 20;
    
    var numbers : i32[10];
    numbers[10] := x;
    ns[10] := x;
    x := ns[10];
    ns[i] := 100;
    
    struct s1 : Sq;
    s1.l := 30;
    s2.l := 20;
    
    add(x, 10);
    add(zz1, zz2);
end

